
using NavMesh2D;
using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;

namespace Navmesh2D
{
    ///<summary>
    /// Structure which lets you compute the constrained delaunay triangulation 
    /// of a given set of vertices and constraints
    ///</summary>
    [BurstCompile]
    public struct ConstrainedDelaunayTriangulation : IJob
    {
        ///<summary>
        /// The triangles generated by the triangulation.
        ///</summary>
        public NativeList<Triangle2D> triangles;
        
        private NativeArray<float2> vertices;
        private NativeList<Triangle2D> badTriangles;
        private NativeList<Edge2D> polygon;
        
        // Buffers to cleanly traverse triangles data(According to the C# Compiler Native collections are Nullable, 
        // because of that the Triangle2D structure cannot contain native arrays to store vertex and edge data.)
        private NativeArray<Edge2D> edgeBuffer;
        private NativeArray<Edge2D> edgeBuffer2;

        private NativeList<Edge2D> intersectingEdges;
        private NativeArray<Edge2D> constraints;
        private NativeArray<Triangle2D> adjacents;
        private NativeArray<Triangle2D> newTriangles;
        
        public ConstrainedDelaunayTriangulation(NativeArray<float2> vertices, NativeArray<Edge2D> constraints)
        {
            this.triangles = new NativeList<Triangle2D>(1, Allocator.TempJob);
            this.badTriangles = new NativeList<Triangle2D>(0, Allocator.TempJob);
            this.edgeBuffer = new NativeArray<Edge2D>(3, Allocator.TempJob);
            this.edgeBuffer2 = new NativeArray<Edge2D>(3, Allocator.TempJob);
            this.polygon = new NativeList<Edge2D>(Allocator.TempJob);
            this.intersectingEdges = new NativeList<Edge2D>(Allocator.TempJob);
            this.adjacents = new NativeArray<Triangle2D>(2, Allocator.TempJob);
            this.newTriangles = new NativeArray<Triangle2D>(2, Allocator.TempJob);
            // Input data.
            this.constraints = constraints;
            this.vertices = vertices;
        }

        public void Execute()
        {
            ConstrainedTriangulation();
        }
        
        private void ConstrainedTriangulation()
        {
            Triangulate();
            
            // Iterate over all constraints to check if they
            // intersect with any edges of the triangles 
            // produced by the Delaunay triangulation.
            foreach (Edge2D constraint in constraints)
            {
                foreach (Triangle2D triangle in triangles)
                {
                    edgeBuffer[0] = triangle.AB;
                    edgeBuffer[1] = triangle.BC;
                    edgeBuffer[2] = triangle.CA;
                    
                    // iterate over all triangle edges and check if they intersect the constraint. If true
                    // add the edge to a list of intersecting edges.
                    foreach (Edge2D edge in edgeBuffer)
                    {
                        if (!constraints.Contains(edge) && MathUtils.LineSegmentIntersection2D(edge.A, edge.B,
                                constraint.A, constraint.B))
                            intersectingEdges.Add(edge);
                    }
                }
                
                for (int i = 0; i < intersectingEdges.Length; i++)
                {
                    Edge2D edge = intersectingEdges[i];
                    
                    int index = 0;
                    
                    foreach(Triangle2D triangle in triangles)
                    {
                        // Does this triangle contain an intersecting edge?
                        if(MathUtils.ContainsEdge(triangle, edge))
                        {
                            adjacents[index] = triangle;
                            index++;
                            // Are there more than two intersecting edges in this triangle?
                            if(index >= 2)
                                break; // If true, stop iterating through all triangles.
                        }
                    }

                    // if this edge intersects 1 or fewer triangles, 
                    // start over from the next iteration.
                    if (index <= 1)
                        continue;
                    
                    Triangle2D t1 = adjacents[0];
                    Triangle2D t2 = adjacents[1];

                    // Get the polygon formed by the two adjacent triangles excluding the intersected edge.
                    edgeBuffer[0] = t1.AB;
                    edgeBuffer[1] = t1.BC;
                    edgeBuffer[2] = t1.CA;
                    edgeBuffer2[0] = t2.AB;
                    edgeBuffer2[1] = t2.BC;
                    edgeBuffer2[2] = t2.CA;
                    polygon = CreatePolygon(ref polygon, edgeBuffer, edgeBuffer2, edge);
                    
                    // Swap edges.
                    int t1Index = triangles.IndexOf(t1);
                    int t2Index = triangles.IndexOf(t2);
                    Edge2D swappedEdge = SwapEdges(t1, t2, edge, newTriangles);
                    triangles[t1Index] = newTriangles[0];
                    triangles[t2Index] = newTriangles[1];
                    
                    // If the swapped edge still intersect our constraint add it to the intersecting edges list.
                    if (MathUtils.LineSegmentIntersection2D(swappedEdge.A, swappedEdge.B,
                            constraint.A, constraint.B, false) &&
                        !Contains(intersectingEdges, swappedEdge))
                        intersectingEdges.Add(swappedEdge);
                }

                // Clear buffered data.
                intersectingEdges.Clear();
            }
            
            // Remove triangles who shares 2 or more edges 
            // with the constraints. this process will form the holes
            // in the mesh geometry.
            for (int i = triangles.Length - 1; i >= 0; i--)
            {
                Triangle2D triangle = triangles[i];
                
                int sharedEdge = 0;
                edgeBuffer[0] = triangle.AB;
                edgeBuffer[1] = triangle.BC;
                edgeBuffer[2] = triangle.CA;
                foreach (Edge2D edge in edgeBuffer)
                    if (constraints.Contains(edge))
                    {
                        sharedEdge++;
                        if (sharedEdge >= 2)
                        {
                            triangles.RemoveAt(i);
                            break;
                        }
                    }
            }
        }
        
        private void Triangulate()
        {
            // Initialize super triangle. Just a placeholder for now.
            Triangle2D superTriangle = new Triangle2D(new float2(-100, -100f), new float2(100, -100f), new float2(0f, 100f));
            triangles.Add(superTriangle);
            
            foreach (float2 vertex in vertices)
            {
                // Check if the current vertex is contained inside triangles
                // circum Circle, if true then mark those triangles as "bad triangles".
                foreach (Triangle2D triangle in triangles)
                {
                    circle2D circle = MathUtils.GetTriangleCircumCircle(triangle);
                    if (MathUtils.ContainsPoint(circle, vertex))
                        badTriangles.Add(triangle);
                }
                
                // For each edge in a bad triangle check if it is shared by at least 1 another bad triangle.
                // If the edge is not shared then add it to the edge buffer.
                foreach (Triangle2D triangle in badTriangles)
                {
                    // Initialize edge buffer
                    edgeBuffer[0] = triangle.AB;
                    edgeBuffer[1] = triangle.BC;
                    edgeBuffer[2] = triangle.CA;
                    foreach (Edge2D edge in edgeBuffer)
                    {
                        bool sharedEdge = false;
                        foreach (Triangle2D otherTriangle in badTriangles)
                        {
                            if (triangle.Equals(otherTriangle))
                                continue;

                            sharedEdge = MathUtils.ContainsEdge(otherTriangle, edge);
                            if (sharedEdge)
                                break;
                        }

                        if (!sharedEdge)
                            polygon.Add(edge);
                    }
                }
                
                // Remove bad triangle from the triangle list.
                foreach (Triangle2D triangle in badTriangles)
                {
                    int index = triangles.IndexOf(triangle);
                    triangles.RemoveAtSwapBack(index);
                }
                
                // Create new triangles using edge points and vertex point.
                foreach (Edge2D edge in polygon)
                {
                    Triangle2D newTriangle = new Triangle2D(vertex, edge.A, edge.B);
                    if(!Contains(triangles, newTriangle))
                        triangles.Add(newTriangle);
                }

                // Clear bad triangles and edge buffers.
                polygon.Clear();
                badTriangles.Clear();
            }

            // Remove triangles which share at least one vertex with the super triangle.
            for (int i = triangles.Length - 1; i >= 0; i--)
            {
                Triangle2D triangle = triangles[i];
                if (MathUtils.ContainsVertex(triangle, superTriangle.A) | MathUtils.ContainsVertex(triangle, superTriangle.B)
                                                              | MathUtils.ContainsVertex(triangle, superTriangle.C))
                    triangles.RemoveAtSwapBack(i);
            }
        }
        
        ///<summary>
        /// Free memory
        ///</summary>
        public void Dispose()
        {
            // Free allocated memory.
            badTriangles.Dispose();
            polygon.Dispose();
            edgeBuffer.Dispose();
            intersectingEdges.Dispose();
            edgeBuffer2.Dispose();
            adjacents.Dispose();
            newTriangles.Dispose();
            vertices.Dispose();
            constraints.Dispose();
        }

        // For some reason NativeList.Contains() is not implemented, that's a workaround which
        // is also compatible with burst compiler.
        private bool Contains(NativeList<Triangle2D> array, Triangle2D element)
        {
            foreach (Triangle2D triangle in array)
                if (triangle.Equals(element))
                    return true;
            return false;
        }
        
        // For some reason NativeList.Contains() is not implemented, that's a workaround which
        // is also compatible with burst compiler.
        private bool Contains(NativeList<Edge2D> array, Edge2D element)
        {
            foreach (Edge2D triangle in array)
                if (triangle.Equals(element))
                    return true;
            return false;
        }

        ///<summary>
        /// Swap the given edge in the given triangles
        ///</summary>
        ///<returns> A Triangle with "Edge" swapped. </returns>
        private Edge2D SwapEdges(Triangle2D t1, Triangle2D t2, Edge2D edge, NativeArray<Triangle2D> triangles)
        {
            Edge2D swappedEdge = edge;
            
            // Swap only if the two triangles shares the same edge.
            if (ContainsEdge(t1, edge) && ContainsEdge(t2, edge))
            {
                NativeArray<Edge2D> t1Edges = new NativeArray<Edge2D>(3, Allocator.Temp);
                t1Edges[0] = t1.AB;
                t1Edges[1] = t1.BC;
                t1Edges[2] = t1.CA;
                // Search for a vertex which is not part of the given edge.
                for (int i = 0; i < 3; i++)
                {
                    Edge2D edge1 = t1Edges[i];
                    if (!edge1.Equals(edge))
                    {
                        if (!MathUtils.ContainsVertex(edge, edge1.A))
                        {
                            swappedEdge.A = edge1.A;
                            break;
                        }

                        if (!MathUtils.ContainsVertex(edge, edge1.B))
                        {
                            swappedEdge.A = edge1.B;
                            break;
                        }
                    }
                }
                
                NativeArray<Edge2D> t2Edges = new NativeArray<Edge2D>(3, Allocator.Temp);
                t2Edges[0] = t2.AB;
                t2Edges[1] = t2.BC;
                t2Edges[2] = t2.CA;
                // Search for a vertex which is not part of the given edge
                for (int i = 0; i < 3; i++)
                {
                    Edge2D edge2 = t2Edges[i];
                    if (!edge2.Equals(edge))
                    {
                        if (!MathUtils.ContainsVertex(edge, edge2.A))
                        {
                            swappedEdge.B = edge2.A;
                            break;
                        }

                        if (!MathUtils.ContainsVertex(edge, edge2.B))
                        {
                            swappedEdge.B = edge2.B;
                            break;
                        }
                    }
                }
                
                //---------- UPDATE TRIANGLE t1------------------------
                // Update given edge.
                int index = t1Edges.IndexOf(edge);
                
                // Update next edge
                int nextIndex = (index + 1) % 3;
                Edge2D temp1 = t1Edges[nextIndex];
                temp1.A = swappedEdge.A;
                temp1.B = edge.A;

                // Get previous element index and keep it inside array bounds.
                int prevIndex = index - 1;
                prevIndex = prevIndex < 0 ? 2 : prevIndex;
                // Update previous edge
                Edge2D temp2 = t1Edges[prevIndex];
                temp2.A = swappedEdge.B;
                temp2.B = edge.A;

                triangles[0] = new Triangle2D(swappedEdge.A, temp1.B, temp2.A);

                //---------- UPDATE TRIANGLE t2------------------------

                index = t2Edges.IndexOf(edge);

                // Update next edge
                nextIndex = (index + 1) % 3;
                temp1 = t2Edges[nextIndex];
                temp1.A = swappedEdge.A;
                temp1.B = edge.B;

                // Get previous element index and keep it inside array bounds.
                prevIndex = index - 1;
                prevIndex = prevIndex < 0 ? 2 : prevIndex;
                // Update previous edge
                temp2 = t2Edges[prevIndex];
                temp2.A = swappedEdge.B;
                temp2.B = edge.B;

                triangles[1] = new Triangle2D(swappedEdge.A, temp1.B, temp2.A);
                
                t1Edges.Dispose();
                t2Edges.Dispose();
            }
            
            return swappedEdge;
        }
        
        private NativeList<Edge2D> CreatePolygon(ref NativeList<Edge2D> polygon, NativeArray<Edge2D> data1, 
                                                 NativeArray<Edge2D> data2, Edge2D intersectingEdge)
        {
            polygon.Clear();
            for(int i = 0; i < 3; i++)
            {
                Edge2D edge1 = data1[i];
                Edge2D edge2 = data2[i];

                if(!edge1.Equals(intersectingEdge))
                  polygon.Add(edge1);

                if(!edge2.Equals(intersectingEdge))
                  polygon.Add(edge2);
            }
            return polygon;
        }
        
        private bool ContainsEdge(Triangle2D triangle, Edge2D edge)
        {
            return triangle.AB.Equals(edge) | triangle.BC.Equals(edge) | triangle.CA.Equals(edge);
        }
    }
}

