using System.Collections;
using System.Collections.Generic;
using NavMesh2D;
using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;
using UnityEngine;

namespace Navmesh2D
{
    ///<summary>
    /// Structure which lets you compute the constrained delaunay triangulation 
    /// of a given set of vertices.
    ///</summary>
    [BurstCompile]
    public struct DelaunayTriangulation : IJob
    {
        ///<summary>
        /// The triangles generated by the triangulation.
        ///</summary>
        public NativeList<Triangle2D> triangles;

        private NativeArray<float2> vertices;
        private NativeList<Triangle2D> badTriangles;
        private NativeList<Edge2D> polygon;
    
        // Buffer to cleanly traverse triangles data(According to the C# Compiler Native collections are Nullable, 
        // because of that the Triangle2D structure cannot contain native arrays to store vertex and edge data.)
        private NativeArray<Edge2D> edgeBuffer;
        
        public DelaunayTriangulation(NativeArray<float2> vertices)
        {
            this.triangles = new NativeList<Triangle2D>(1, Allocator.TempJob);
            this.badTriangles = new NativeList<Triangle2D>(0, Allocator.TempJob);
            this.edgeBuffer = new NativeArray<Edge2D>(3, Allocator.TempJob);
            this.polygon = new NativeList<Edge2D>(Allocator.TempJob);
            this.vertices = vertices;
        }

        public void Execute()
        {
            Triangulate();
        }

        public void Triangulate()
        {
            // Initialize super triangle. Just a placeholder for now.
            Triangle2D superTriangle = new Triangle2D(new float2(-100, -100f), new float2(100, -100f), new float2(0f, 100f));
            triangles.Add(superTriangle);
            
            foreach (float2 vertex in vertices)
            {
                // Check if the current vertex is contained inside triangles
                // circum Circle, if true then mark those triangles as "bad triangles".
                foreach (Triangle2D triangle in triangles)
                {
                    circle2D circle = MathUtils.GetTriangleCircumCircle(triangle);
                    if (MathUtils.ContainsPoint(circle, vertex))
                        badTriangles.Add(triangle);
                }
                
                // For each edge in a bad triangle check if it is shared by at least 1 another bad triangle.
                // If the edge is not shared then add it to the edge buffer.
                foreach (Triangle2D triangle in badTriangles)
                {
                    // Initialize edge buffer
                    edgeBuffer[0] = triangle.AB;
                    edgeBuffer[1] = triangle.BC;
                    edgeBuffer[2] = triangle.CA;
                    foreach (Edge2D edge in edgeBuffer)
                    {
                        bool sharedEdge = false;
                        foreach (Triangle2D otherTriangle in badTriangles)
                        {
                            if (triangle.Equals(otherTriangle))
                                continue;

                            sharedEdge = MathUtils.ContainsEdge(otherTriangle, edge);
                            if (sharedEdge)
                                break;
                        }

                        if (!sharedEdge)
                            polygon.Add(edge);
                    }
                }
                
                // Remove bad triangle from the triangle list.
                foreach (Triangle2D triangle in badTriangles)
                {
                    int index = triangles.IndexOf(triangle);
                    triangles.RemoveAtSwapBack(index);
                }
                
                // Create new triangles using edge points and vertex point.
                foreach (Edge2D edge in polygon)
                {
                    Triangle2D newTriangle = new Triangle2D(vertex, edge.A, edge.B);
                    if(!Contains(triangles, newTriangle))
                        triangles.Add(newTriangle);
                }

                // Clear bad triangles and edge buffers.
                polygon.Clear();
                badTriangles.Clear();
            }

            // Remove triangles which share at least one vertex with the super triangle.
            for (int i = triangles.Length - 1; i >= 0; i--)
            {
                Triangle2D triangle = triangles[i];
                if (MathUtils.ContainsVertex(triangle, superTriangle.A) | MathUtils.ContainsVertex(triangle, superTriangle.B) 
                                                                        | MathUtils.ContainsVertex(triangle, superTriangle.C))
                    triangles.RemoveAtSwapBack(i);
            }
        }
        
        ///<summary>
        /// Free memory
        ///</summary>
        public void Dispose()
        {
            // Free allocated memory.
            badTriangles.Dispose();
            polygon.Dispose();
            edgeBuffer.Dispose();
        }
        
        // For some reason NativeList.Contains() is not implemented, that's a workaround which
        // is also compatible with burst compiler.
        private bool Contains(NativeList<Triangle2D> array, Triangle2D element)
        {
            foreach (Triangle2D triangle in array)
                if (triangle.Equals(element))
                    return true;
            return false;
        }
    }
}

